league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:JWT_SECRET_KEY)%'
        private_key_passphrase: '%env(JWT_PASSPHRASE)%'
        encryption_key: '%env(SYLIUS_ADMIN_MCP_SERVER_OAUTH_ENCRYPTION_KEY)%'
        encryption_key_type: 'plain'
        enable_client_credentials_grant: false
        enable_password_grant: false
        enable_implicit_grant: false
        persist_access_token: false

    resource_server:
        public_key: '%env(resolve:JWT_PUBLIC_KEY)%'

    scopes:
        available:
            - admin_api
        default:
            - admin_api

    persistence:
        in_memory: ~
