ajgarlag_openid_connect_provider:
    discovery:
        authorization_endpoint_route: 'oauth2_authorize'
        token_endpoint_route: 'oauth2_token'
        jwks_endpoint_route: 'openid_connect_jwks'
        end_session_endpoint_route: 'openid_connect_end_session'
    end_session:
        cancel_logout_default_path: '/'
