php_version = "8.2"

[source]
paths = [
  "src/",
  "config/",
  "bin/",
  # "tests/",
  # "importmap.php",
  # "migrations/",
]
includes = ["vendor"]
excludes = []

[format]
print_width = 120
tab_width = 4
use_tabs = false

# [linter]
# default_plugins = true
# plugins = ["symfony"]
