services:
    kafka:
        image: apache/kafka:4.0.0
        hostname: ${KAFKA_HOSTNAME:-kafka}
        container_name: ${KAFKA_CONTAINER_NAME:-kafka}
        ports:
            - "${KAFKA_CONTAINER_PORT:-9092}:9092"
            - "${KAFKA_CONTAINER_INTERNAL_PORT:-29092}:29092"
        networks:
            - ${KAFKA_NETWORK:-default}
        environment:
            KAFKA_BROKER_ID: ${KAFKA_CONTAINER_BROKER_ID:-1}
            KAFKA_NODE_ID: ${KAFKA_CONTAINER_NODE_ID:-1}
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "${KAFKA_CONTAINER_QUORUM_VOTERS:-1@kafka:9093}"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_CONTAINER_ADVERTISED_HOST:-kafka}:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            CLUSTER_ID: ${KAFKA_CONTAINER_CLUSTER_ID}
