storyblok:
    base_uri: '%env(STORYBLOK_API_BASE_URI)%'
    token: '%env(STORYBLOK_API_TOKEN)%'
    version: '%env(STORYBLOK_VERSION)%'
    # assets_token: '%env(STORYBLOK_ASSETS_API_TOKEN)%'
    # webhook_secret: '%env(STORYBLOK_WEBHOOK_SECRET)%'
    # auto_resolve_relations: true
    # controller:
    #     ascending_redirect_fallback: true

when@prod:
    storyblok:
        controller:
            cache:
                public: true
                max_age: 3600
                smax_age: 3600
                must_revalidate: true
