letkode_form_schema:
    default_locale: es
    available_locales:
        - es
        - en
        - pt
    entity_namespace: App\Entity
    table_prefix: ''
    seeds_path: '%kernel.project_dir%/config/seeds/form_schema'
    table_names:
        form: null
        form_section: null
        form_group: null
        form_field: null
        form_option: null
        form_option_value: null
    cache:
        enabled: false
        pool: cache.app
        ttl: 3600
        key_prefix: fsb
        auto_invalidate: true
    disabled_field_types: []
    disabled_options_sources: []
    disabled_form_renders: []
    disabled_section_renders: []
    disabled_group_renders: []
