apex_toolbox:
    token: '%env(APEX_TOOLBOX_TOKEN)%'
    enabled: true

    # Path filtering for HTTP tracking
    path_filters:
        include:
            - 'api/*'        # Track all API routes
            # - '*'          # Uncomment to track ALL routes
        exclude:
            - 'api/health'   # Skip health checks
            - 'api/ping'     # Skip ping endpoints

    # Header filtering
    headers:
        exclude:
            - 'authorization'
            - 'x-api-key'
            - 'cookie'

    # Request body filtering
    body:
        exclude:
            - 'password'
            - 'password_confirmation'
            - 'token'
            - 'secret'
            - 'access_token'
            - 'refresh_token'
            - 'api_key'
            - 'private_key'
        mask:
            - 'ssn'
            - 'social_security'
            - 'phone'
            - 'email'
            - 'address'
            - 'postal_code'
            - 'zip_code'

    # Response filtering
    response:
        exclude:
            - 'password'
            - 'token'
            - 'secret'
            - 'access_token'
            - 'refresh_token'
            - 'api_key'
            - 'private_key'
        mask:
            - 'ssn'
            - 'social_security'
            - 'phone'
            - 'email'

    # Universal logging (console commands, workers)
    universal_logging:
        enabled: true
        types:
            - 'http'
            - 'console'
            - 'queue'
