gurtok_seo:
    # this switch off validation of meta tags (other case will be validated by MetaTag enum)
    allow_custom_meta: false
    # this switch on auto inject of meta tags in response
    auto_inject_response: false
    # this parameter is used to exclude some paths from auto inject of seo response
    excluded_paths:
#        - /admin
#        - /api
