name: Cleanup Flex testing endpoint

on:
    pull_request_target:
        types: [ closed ]

defaults:
    run:
        shell: bash

jobs:
    call-flex-cleanup:
        uses: symfony/recipes/.github/workflows/callable-flex-cleanup.yml@a0f880a116fad71183707149d747cbde9ec89593 # main (2026-07-28)
